name: Tests
on: [pull_request]

jobs:
  test-with-csp:
    env:
      CSP: '1'
    name: +CSP
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          yarn
          yarn setup
      - name: Test Chrome
        run: yarn build-test-chrome
      - name: Test FireFox
        run: yarn build-test-firefox
      - name: Test Safari
        run: yarn build-test-safari
  test-without-csp:
    env:
      CSP: '0'
    name: -CSP
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          yarn
          yarn setup
      - name: Test Chrome
        run: yarn build-test-chrome
      - name: Test FireFox
        run: yarn build-test-firefox
      - name: Test Safari
        run: yarn build-test-safari