name: Tests
on: [pull_request]

jobs:
  test-with-csp:
    name: +CSP
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Test Chrome
        run: export CSP=1;yarn build-test-chrome
      - name: Test FireFox
        run: export CSP=1;yarn build-test-firefox
      - name: Test Safari
        run: export CSP=1;yarn build-test-safari
  test-without-csp:
    name: -CSP
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Test Chrome
        run: export CSP=0;yarn build-test-chrome
      - name: Test FireFox
        run: export CSP=0;yarn build-test-firefox
      - name: Test Safari
        run: export CSP=0;yarn build-test-safari