name: CI
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts
      - name: Test Chrome
        run: yarn build-test-chrome
      - name: Test FireFox
        run: yarn build-test-firefox
      - name: Test Safari
        run: yarn build-test-safari
