name: Tests
on: [pull_request]

jobs:
  test:
    name: CSP=${{ matrix.csp }}
    runs-on: macos-14
    strategy:
      matrix:
        csp: ['0', '1']
    env:
      CSP: ${{ matrix.csp }}
    steps:
      - name: log env var used
        run: echo $CSP
      - name: Check Firefox installation
        id: check-firefox
        run: |
          which firefox || echo "Firefox not found" && echo "firefox_missing=true" >> $GITHUB_OUTPUT
      - name: Install Firefox
        if: steps.check-firefox.outputs.firefox_missing == 'true'
        run: |
          brew install --cask firefox
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: |
          yarn
          yarn setup
      - name: Test Chrome
        run: yarn build-test-chrome
      - name: Test FireFox
        run: yarn build-test-firefox
      - name: Test Safari
        run: yarn build-test-safari
