name: CI
on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Build Snow
        run: yarn build
      - name: Verify No Change
        run: 'git diff-index --quiet HEAD -- || (echo "There are unstaged files. Aborting the workflow." && exit 1)'
      - name: Test Chrome
        run: yarn build-test-chrome
      - name: Test FireFox
        run: yarn build-test-firefox
      - name: Test Safari
        run: yarn build-test-safari
